apiVersion: v1
kind: ConfigMap
metadata:
  name: services-config
  namespace: microservices
data:
  AUTH_SERVICE_URL: "http://auth-service.microservices.svc.cluster.local"
  ORDER_SERVICE_URL: "http://order-service.microservices.svc.cluster.local"
  PAYMENT_SERVICE_URL: "http://payment-service.microservices.svc.cluster.local"
  NOTIFICATION_SERVICE_URL: "http://notification-service.microservices.svc.cluster.local"
  LOG_LEVEL: "INFO"
  XRAY_DAEMON_ADDRESS: "xray-daemon.microservices.svc.cluster.local:2000"
